#-*- coding: utf-8 -*-

{
	"name": "Informasi",
	"version": "1.1", 
	"depends": [
		'base','vit_univ_common',
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Informasi module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/agenda.xml",
		# "view/unit_kerja.xml",
		"view/berita.xml",
		"view/jenis_dokumen.xml",
		"view/dokumen_satuan_kerja.xml",
		"view/dokumen.xml",
		"view/image_slider.xml",
		"report/agenda.xml",
		"report/unit_kerja.xml",
		"report/berita.xml",
		"report/jenis_dokumen.xml",
		"report/dokumen_satuan_kerja.xml",
		"report/dokumen.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}