#-*- coding: utf-8 -*-

{
	"name": "Remunerasi",
	"version": "1.0", 
	"depends": [
		'base','hr','vit_univ_common','vit_skp',
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Remunerasi module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/jenis_insentif_kinerja.xml",
		"view/jenis_sub_insentif_kinerja.xml",
		# "view/employee.xml",
		"view/grade_per_pegawai_detail.xml",
		"view/gaji_pnbp_detail.xml",
		"view/pir_detail.xml",
		"view/tunkin_kehadiran_detail.xml",
		"view/kehadiran_pegawai_detail.xml",
		"view/remunerasi_pegawai_ids.xml",
		"view/capaian_kinerja_unit_kerja_detail.xml",
		# "view/unit_kerja.xml",
		"view/grade_per_pegawai.xml",
		"view/gaji_pnbp.xml",
		"view/pir.xml",
		"view/tunkin_terlambat_detail.xml",
		"view/tunkin_pulang_detail.xml",
		"view/tunkin_pemotongan_detail.xml",
		"view/tunkin_kehadiran.xml",
		"view/tunkin_terlambat.xml",
		"view/tunkin_pulang.xml",
		"view/tunkin_pemotongan.xml",
		"view/kehadiran_pegawai.xml",
		"view/remunerasi_pegawai.xml",
		"view/capaian_kinerja_unit_kerja.xml",
		"report/jenis_insentif_kinerja.xml",
		"report/jenis_sub_insentif_kinerja.xml",
		"report/employee.xml",
		"report/grade_per_pegawai_detail.xml",
		"report/gaji_pnbp_detail.xml",
		"report/pir_detail.xml",
		"report/tunkin_kehadiran_detail.xml",
		"report/kehadiran_pegawai_detail.xml",
		"report/remunerasi_pegawai_ids.xml",
		"report/capaian_kinerja_unit_kerja_detail.xml",
		"report/unit_kerja.xml",
		"report/grade_per_pegawai.xml",
		"report/gaji_pnbp.xml",
		"report/pir.xml",
		"report/tunkin_terlambat_detail.xml",
		"report/tunkin_pulang_detail.xml",
		"report/tunkin_pemotongan_detail.xml",
		"report/tunkin_kehadiran.xml",
		"report/tunkin_terlambat.xml",
		"report/tunkin_pulang.xml",
		"report/tunkin_pemotongan.xml",
		"report/kehadiran_pegawai.xml",
		"report/remunerasi_pegawai.xml",
		"report/capaian_kinerja_unit_kerja.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}