#-*- coding: utf-8 -*-

{
	"name": "E-Office",
	"version": "1.0", 
	"depends": [
		'base',
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the E-Office module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/doc.xml",
		# "view/user.xml",
		"view/to_user.xml",
		"view/cc_user.xml",
		"view/doc_type.xml",
		"view/doc_template.xml",
		"view/doc_history.xml",
		"report/doc.xml",
		"report/user.xml",
		"report/to_user.xml",
		"report/cc_user.xml",
		"report/doc_type.xml",
		"report/doc_template.xml",
		"report/doc_history.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}