#-*- coding: utf-8 -*-

{
	"name": "Kantor",
	"version": "1.0", 
	"depends": [
		'base','vit_asset',
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Kantor module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/pebin.xml",
		"view/pbi.xml",
		"view/ppbi.xml",
		"view/kanwil.xml",
		"view/kppn.xml",
		"view/kpknl.xml",
		# "view/lokasi.xml",
		"view/wilayah.xml",
		"report/pebin.xml",
		"report/pbi.xml",
		"report/ppbi.xml",
		"report/kanwil.xml",
		"report/kppn.xml",
		"report/kpknl.xml",
		"report/lokasi.xml",
		"report/wilayah.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}