#-*- coding: utf-8 -*-

{
	"name": "Pemakaian",
	"version": "1.0", 
	"depends": [
		'base','hr','om_account_asset','vit_asset','vit_univ_common',
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Pemakaian module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		# "view/menu.xml",
		"view/pemakaian_aset.xml",
		# "view/unit_kerja.xml",
		# "view/jurusan.xml",
		# "view/fakultas.xml",
		# "view/aset.xml",
		# "view/employee.xml",
		"view/aset_pemakaian.xml",
		# "view/category.xml",
		# "view/lokasi.xml",
		"report/pemakaian_aset.xml",
		"report/unit_kerja.xml",
		"report/jurusan.xml",
		"report/fakultas.xml",
		"report/aset.xml",
		"report/employee.xml",
		"report/aset_pemakaian.xml",
		"report/category.xml",
		"report/lokasi.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}