#!/usr/bin/python
from . import bkd
from . import employee
from . import tahun_akademik
from . import company
from . import semester
from . import status_dosen
from . import fakultas
from . import jurusan
from . import program_studi
from . import jabatan
from . import golongan
from . import kinerja_bidang_pendidikan
from . import jenis_kegiatan_pendidikan
from . import rekomendasi
from . import kinerja_bidang_penelitian
from . import jenis_kegiatan_penelitian
from . import kinerja_bidang_pengabdian
from . import jenis_kegiatan_pengabdian
from . import kinerja_kewajiban_khusus
from . import jenis_kegiatan_kewajiban_khusus
from . import pernyataan_asesor
from . import rekap_fakultas
from . import rekap_fakultas_line
from . import rekap_perguruan_tinggi
from . import rekap_perguruan_tinggi_line
from . import kesimpulan_kinerja_dosen
from . import kesimpulan_kinerja_dosen_line
# from . import permintaan_bkd
from . import kinerja_penunjang
from . import jenis_karya
from . import syarat_bkd
from . import kesimpulan_kewajiban_khusus_line