#-*- coding: utf-8 -*-

{
	"name": "Kerja Dosen Inherited",
	"version": "1.1", 
	"depends": [
		'base','hr',
		'vit_kerja_dosen','vit_univ_common','vit_univ_common_inherit','vit_bkd',
	],
	"author": "Soni [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Kerja Dosen module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"data/sequence_pengajuan_dosen.xml",
		"data/sequence_persetujuan_beban_kinerja_dosen.xml",
		"data/sequence_usulan_sertifikasi.xml",
		"data/sequence_verifikasi_data_dosen.xml",
		"data/sequence_penelitian_sertifikasi.xml",
		"view/pengajuan_dosen.xml",
		"view/beban_kinerja.xml",
		"view/usulan_sertifikasi.xml",
		"view/sertifikasi_dosen.xml",
		"view/verifikasi.xml",
		"view/penelitian_sertifikasi.xml",
		"view/vit_kerja_dosen.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}