#-*- coding: utf-8 -*-

{
	"name": "Beasiswa",
	"version": "1.0", 
	"depends": [
		'base','vit_univ_common',
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Beasiswa module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/penerima_beasiswa.xml",
		# "view/institusi.xml",
		# "view/fakultas.xml",
		# "view/jurusan.xml",
		"view/prestasi_akademik.xml",
		"report/penerima_beasiswa.xml",
		"report/institusi.xml",
		"report/fakultas.xml",
		"report/jurusan.xml",
		"report/prestasi_akademik.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}