#-*- coding: utf-8 -*-

{
	"name": "Tata Kelola Surat",
	"version": "1.0", 
	"depends": [
		'base','vit_univ_common','om_account_asset','vit_asset','uom','vit_gedung_ruang',
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Tata Kelola Surat module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/kir.xml",
		"view/kir_detail.xml",
		"view/buku_inventaris.xml",
		# "view/lokasi.xml",
		"view/buku_inventaris_detail.xml",
		"view/buku_induk_inventaris.xml",
		"view/buku_induk_inventaris_detail.xml",
		# "view/asset_asset.xml",
		# "view/uom.xml",
		"view/mutasi_barang.xml",
		# "view/vit_transfer.xml",
		"view/mutasi_detail.xml",
		# "view/category.xml",
		# "report/kir.xml",
		# "report/kir_detail.xml",
		# "report/buku_inventaris.xml",
		# "report/lokasi.xml",
		# "report/buku_inventaris_detail.xml",
		# "report/buku_induk_inventaris.xml",
		# "report/buku_induk_inventaris_detail.xml",
		# "report/asset_asset.xml",
		# "report/uom.xml",
		# "report/mutasi_barang.xml",
		# "report/vit_transfer.xml",
		# "report/mutasi_detail.xml",
		# "report/category.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}