#-*- coding: utf-8 -*-

{
	"name": "Kerja Dosen",
	"version": "1.0", 
	"depends": [
		'base','hr',
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Kerja Dosen module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/pengajuan_dosen.xml",
		# "view/employee.xml",
		"view/persetujuan_beban_kinerja_dosen.xml",
		"view/usulan_sertifikasi.xml",
		"view/verifikasi_data_dosen.xml",
		"view/penelitian_sertifikasi.xml",
		"report/pengajuan_dosen.xml",
		"report/employee.xml",
		"report/persetujuan_beban_kinerja_dosen.xml",
		"report/usulan_sertifikasi.xml",
		"report/verifikasi_data_dosen.xml",
		"report/penelitian_sertifikasi.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}