#-*- coding: utf-8 -*-

{
	"name": "cash_in_cash_out",
	"version": "1.0", 
	"depends": [
		'base','account','account_accountant',
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the cash_in_cash_out module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/cash_in_out.xml",
		# "data/sequence_cash_in_out.xml",
		"view/transaksi_cash.xml",
		"report/paperformat.xml",
		"report/template.xml",
		"report/cash_in_out.xml",
		"report/transaksi_cash.xml",
		"wizard/report_cash_in_out.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}