#-*- coding: utf-8 -*-

{
	"name": "Tata Kelola Surat Inherited",
	"version": "1.0", 
	"depends": [
		'base','hr','vit_univ_common','om_account_asset','vit_asset','uom',
		'vit_tks','vit_gedung_ruang'
	],
	"author": "SLH[vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Tata Kelola Surat module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"data/sequence_kir.xml",
		"data/sequence_buku_inventaris.xml",
		"data/sequence_buku_induk_inventaris.xml",
		"data/sequence_mutasi_barang.xml",
		"view/aset.xml",
		"view/kir.xml",
		"view/buku_induk_inventaris.xml",
		"view/buku_inventaris.xml",
		"view/mutasi.xml",
		"report/buku_induk_inventaris.xml",
		"report/buku_inventaris.xml",
		"report/kir.xml",
		"report/mutasi.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}