#!/usr/bin/python
from . import employee
from . import riwayat_izin_belajar
from . import riwayat_tugas_belajar
from . import riwayat_study_lanjutan
from . import riwayat_bkd
from . import riwayat_pengabdian_masyarakat
from . import riwayat_pekerjaan
from . import riwayat_beasiswa
from . import riwayat_diklat
from . import riwayat_pendidikan
from . import riwayat_penghargaan
from . import riwayat_penelitian_karya_imliah
from . import riwayat_dosen_mengajar_diluar
from . import riwayat_seminar
from . import riwayat_organisasi_pegawai
from . import riwayat_pelatihan
from . import riwayat_kunjungan_ke_luar_negeri
from . import riwayat_kepakaran_dosen
from . import riwayat_mengajar
from . import riwayat_membimbing
from . import country
from . import partner
from . import strata
from . import verifikasi