#-*- coding: utf-8 -*-

{
	"name": "Referensi Pegawai",
	"version": "1.0", 
	"depends": [
		'base','hr','mail','vit_univ_common','vit_univ_common_inherit','vit_bkd','vit_bkd_inherit',
		'hr_payroll',
	],
	"author": "Soni [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Referensi module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/referensi_pegawai.xml",
		"view/pak_kegiatan.xml",
		"view/jenis_buku.xml",
		"view/jenis_pendidikan.xml",
		"view/ref_pendidikan.xml",
		"view/jenis_pegawai.xml",
		"view/asal_dana.xml",
		"view/ref_level.xml",
		"view/nikah.xml",
		"view/jenis_penelitian.xml",
		"view/peranan_penelitian.xml",
		"view/employee.xml",
		"view/referensi_rekomendasi_bkd.xml",
		"view/jabatan.xml",
		"view/kinerja.xml",
		"view/pendapat.xml",
		"view/jenis_jabatan.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}