#-*- coding: utf-8 -*-

{
	"name": "Marketing Request",
	"version": "2.0", 
	"depends": [
		'base','mrp','stock','product','uom','vit_marketing','vit_marketing_inherit', 'vit_marketing_sph_garmen', 'vit_product_request'
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit marketing request module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"data/squence.xml",
		"data/product_category.xml",
		"security/group.xml",
		"security/ir.model.access.csv",
		"wizard/request_wizard.xml",
		"wizard/product_request.xml",
		"view/menu.xml",
		"view/product.xml",
		"view/marketing_request.xml",
		"view/request_line.xml",
		"view/production.xml",
        "view/product_request.xml",
		"report/layout.xml",
		"report/paper.xml",
		"report/marketing_request.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}