#-*- coding: utf-8 -*-

{
	"name": "Kelompok Aset",
	"version": "1.0", 
	"depends": [
		'base','vit_asset','om_account_asset',
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Kelompok dan Pemilk Aset module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		# "view/menu.xml",
		"view/kelompok_aset.xml",
		"view/account_asset.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}