#-*- coding: utf-8 -*-

{
	"name": "E-Office Inherited",
	"version": "1.0", 
	"depends": [
		'base', 'mail',
		'vit_eoffice'
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the E-Office module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"data/sequence_doc.xml",
		"data/doc_template.xml",
		"data/doc_type.xml",
		"view/doc.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}