#-*- coding: utf-8 -*-

{
	"name": "Mutasi Inherited",
	"version": "1.0", 
	"depends": [
		'base','hr','vit_univ_common','vit_mutasi','vit_skp'
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Mutasi module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"data/sequence_mutasi_status_pegawai.xml",
		"data/sequence_mutasi_unit_kerja.xml",
		"data/sequence_mutasi_pangkat_golongan.xml",
		"data/sequence_mutasi_jabatan.xml",
		"data/sequence_mutasi_kenaikan_gaji_berkala.xml",
		"data/sequence_mutasi_penyesuaian_masa_kerja.xml",
		"data/sequence_mutasi_pengajuan_angka_kredit.xml",
		"data/sequence_mutasi_penetapan_angka_kredit.xml",
		"data/sequence_mutasi_hukum.xml",
		"data/sequence_mutasi_jabatan_struktural.xml",
		"data/sequence_mutasi_skp.xml",
		"view/mutasi_jabatan.xml",
		"view/mutasi_hukuman.xml",
		"view/mutasi_status_pegawai.xml",
		"view/mutasi_unit_kerja.xml",
		"view/mutasi_kenaikan_gaji.xml",
		"view/mutasi_pang_gol.xml",
		"view/mutasi_pengajuan_ak.xml",
		"view/mutasi_pak.xml",
		"view/mutasi_peny_masa_kerja.xml",
		"view/mutasi_jabatan_struktural.xml",
		"view/mutasi_jabatan_struktural_detail.xml",
		"view/employee.xml",
		"view/mutasi_gaji_detail.xml",
		"view/mutasi_skp.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}