#-*- coding: utf-8 -*-

{
	"name": "Pemakaian Inherited",
	"version": "1.0", 
	"depends": [
		'base','hr','om_account_asset','vit_asset','vit_univ_common',
		'vit_pemakaian_aset'
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Pemakaian module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"data/sequence_pemakaian_aset.xml",
		"view/pemakaian.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}