#-*- coding: utf-8 -*-

{
	"name": "Vit marketing po garmen",
	"version": "1.8", 
	"depends": [
		'base','stock','product','uom','vit_marketing','vit_marketing_inherit','vit_marketing_sph_garmen'
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit marketing po module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"data/squence.xml",
		"security/group.xml",
		"security/ir.model.access.csv",
		# "view/menu.xml",
		"view/purchase_order.xml",
		"view/product_template.xml",
		# "view/boq_po_line.xml",
		"view/document_po_line.xml",
		"report/purchase_order.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}