#-*- coding: utf-8 -*-

{
	"name": "Remunerasi Inherited",
	"version": "1.2", 
	"depends": [
		'base','hr','hr_contract','hr_payroll','hr_attendance','vit_univ_common',
		'vit_remunerasi'
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Remunerasi module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"data/sequence_grade_per_pegawai.xml",
		"data/sequence_gaji_pnbp.xml",
		"data/sequence_pir.xml",
		"data/sequence_tunkin_kehadiran.xml",
		"data/sequence_tunkin_terlambat.xml",
		"data/sequence_tunkin_pulang.xml",
		"data/sequence_tunkin_pemotongan.xml",
		"data/sequence_kehadiran_pegawai.xml",
		"data/sequence_remunerasi_pegawai.xml",
		"data/sequence_capaian_kinerja_unit_kerja.xml",
		"view/menu.xml",
		"view/vit_remunerasi.xml",
		"view/views.xml",
		"report/remunerasi_pegawai.xml",
		"report/capaian_kinerja_unit_kerja.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}