#-*- coding: utf-8 -*-

{
	"name": "Informasi Inherited",
	"version": "1.1", 
	"depends": [
		'base','vit_univ_common',
		'vit_dokumen'
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Informasi module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
	"security/ir.model.access.csv",
	"view/vit_informasi.xml",
	"view/views.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}