#-*- coding: utf-8 -*-

{
	"name": "Gedung dan Ruang Inherited",
	"version": "1.0", 
	"depends": [
		'base','vit_univ_common','om_account_asset','vit_asset',
		'vit_gedung_ruang'
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Gedung dan Ruang module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"data/sequence_vit_gedung.xml",
		"view/gedung.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}