#!/usr/bin/python
from . import laporan_daftar_pegawai
from . import fakultas
from . import golongan
from . import laporan_detail
from . import laporan_statistik_pegawai
from . import matra
from . import lap_statistik_detail
from . import daftar_riwayat_hidup
from . import daftar_detail
from . import duk
from . import duk_detail
from . import daftar_guru_besar
from . import gb_detail
from . import tenaga_fungsional
from . import tf_detail
from . import jabatan
from . import dp3
from . import detail_penilaian
from . import kenaikan_gaji
from . import details_gaji
from . import kenaikan_pangkat
from . import details_naik_pangkat
from . import daftar_pegawai_pensiun
from . import pensiun_detail
from . import lap_nominatif
from . import nom_detail
from . import penerimaan_penghargaan
from . import detail_penerimaan_penghargaan