#-*- coding: utf-8 -*-

{
	"name": "Rekap Anggaran",
	"version": "1.0", 
	"depends": [
		'base','vit_univ_common','uom','anggaran',
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Rekap Anggaran module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"data/sequence_rekapitulasi_anggaran_program_dan_kegiatan_unit.xml",
		"data/sequence_rekap_anggaran_program.xml",
		"data/sequence_rekap_unit.xml",
		# "view/menu.xml",
		"view/rekapitulasi_anggaran_program_dan_kegiatan_unit.xml",
		# "view/account_fiscal_year.xml",
		# "view/account_period.xml",
		"view/anggaran_detail.xml",
		# "view/kegiatan.xml",
		# "view/unit.xml",
		# "view/program.xml",
		"view/rekap_anggaran_program.xml",
		"view/anggaran_program.xml",
		"view/rekap_program.xml",
		# "view/uom.uom.xml",
		"view/rekap_unit.xml",
		"view/anggaran_unit.xml",
		"view/anggaran_rasio.xml",
		"report/rekapitulasi_anggaran_program_dan_kegiatan_unit.xml",
		# "report/account_fiscal_year.xml",
		# "report/account_period.xml",
		"report/anggaran_detail.xml",
		# "report/kegiatan.xml",
		# "report/unit.xml",
		# "report/program.xml",
		"report/rekap_anggaran_program.xml",
		"report/anggaran_program.xml",
		"report/rekap_program.xml",
		# "report/uom.uom.xml",
		"report/rekap_unit.xml",
		"report/rka.xml",
		"report/rka_detail.xml",
		"report/anggaran_unit.xml",
		"report/anggaran_rasio_report.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}