#!/usr/bin/python
from . import skp
from . import tahun_akademik
from . import employee
from . import skp_perkuliahan
from . import skp_seminar
from . import skp_kkn_pkn_pkl
from . import skp_disertasi
from . import skp_penguji
from . import skp_membina
from . import skp_mengembangkan_program_kuliah
from . import skp_mengembangkan_bahan_kuliah
from . import skp_orasi_ilmiah
from . import skp_jabatan_pt
from . import skp_membimbing_dosen
from . import skp_detasering
from . import skp_pengembangan_diri
from . import skp_penelitian
from . import skp_pengabdian
from . import semester
from . import skp_rekapitulasi_perkuliahan
from . import jenis_kkn
from . import jenis_disertasi
from . import skp_rekapitulasi_mengembangkan_bahan_kuliah
from . import skp_rekapitulasi_jabatan_pt
from . import jabatan
from . import unit_kerja
from . import target_skp
from . import skp_tugas_tambahan
from . import penilaian_skp
from . import monitoring_skp