#-*- coding: utf-8 -*-

{
	"name": "BKD Inherited",
	"version": "1.0", 
	"depends": [
		'base','hr','vit_univ_common',
		'vit_bkd'
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the BKD module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"data/sequence_bkd.xml",
		"data/sequence_pernyataan_asesor.xml",
		"data/sequence_rekap_fakultas.xml",
		"data/sequence_rekap_perguruan_tinggi.xml",
		"data/sequence_kesimpulan_kinerja_dosen.xml",
		"data/sequence_perm_bkd.xml",
		# "view/perm_bkd.xml",
		"view/employee.xml",
		"view/bkd.xml",
		"view/rekap.xml",
		"view/kesimpulan.xml",
		"view/pernyataan.xml",
		"view/kinerja_penunjang.xml",
		"view/jenis_karya.xml",
		"view/kinerja_kewajiban_khusus.xml",
		"view/syarat_bkd.xml",
		"report/template.xml",
		"report/report_rkd.xml",
		"report/report_bkd.xml",
		"report/kesimpulan_bkd.xml",
		"report/kesimpulan_khusus.xml",
		"report/rekap_fakultas.xml",
		"report/rekap_perguruan_tinggi.xml",
		# "report/permintaan_bkd.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}