#-*- coding: utf-8 -*-

{
	"name": "Vit riwayat",
	"version": "1.0", 
	"depends": [
		'base','hr'
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit riwayat module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"view/menu.xml",
		# "view/employee.xml",
		"view/riwayat_izin_belajar.xml",
		"view/riwayat_tugas_belajar.xml",
		"view/riwayat_study_lanjutan.xml",
		"view/riwayat_bkd.xml",
		"view/riwayat_pengabdian_masyarakat.xml",
		"view/riwayat_pekerjaan.xml",
		"view/riwayat_beasiswa.xml",
		"view/riwayat_diklat.xml",
		"view/riwayat_pendidikan.xml",
		"view/riwayat_penghargaan.xml",
		"view/riwayat_penelitian_karya_imliah.xml",
		"view/riwayat_dosen_mengajar_diluar.xml",
		"view/riwayat_seminar.xml",
		"view/riwayat_organisasi_pegawai.xml",
		"view/riwayat_pelatihan.xml",
		"view/riwayat_kunjungan_ke_luar_negeri.xml",
		"view/riwayat_kepakaran_dosen.xml",
		"view/riwayat_mengajar.xml",
		"view/riwayat_membimbing.xml",
		# "view/country.xml",
		# "view/partner.xml",
		"view/strata.xml",
		"view/riwayat_perjalanan_dinas.xml",
		"report/employee.xml",
		"report/riwayat_izin_belajar.xml",
		"report/riwayat_tugas_belajar.xml",
		"report/riwayat_study_lanjutan.xml",
		"report/riwayat_bkd.xml",
		"report/riwayat_pengabdian_masyarakat.xml",
		"report/riwayat_pekerjaan.xml",
		"report/riwayat_beasiswa.xml",
		"report/riwayat_diklat.xml",
		"report/riwayat_pendidikan.xml",
		"report/riwayat_penghargaan.xml",
		"report/riwayat_penelitian_karya_imliah.xml",
		"report/riwayat_dosen_mengajar_diluar.xml",
		"report/riwayat_seminar.xml",
		"report/riwayat_organisasi_pegawai.xml",
		"report/riwayat_pelatihan.xml",
		"report/riwayat_kunjungan_ke_luar_negeri.xml",
		"report/riwayat_kepakaran_dosen.xml",
		"report/riwayat_mengajar.xml",
		"report/riwayat_membimbing.xml",
		"report/country.xml",
		"report/partner.xml",
		"report/strata.xml",
		"report/riwayat_perjalanan_dinas.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}