#!/usr/bin/python
from . import mutasi_status_pegawai
from . import employee
from . import status_pegawai
from . import mutasi_unit_kerja
from . import unit_kerja
from . import mutasi_pangkat_golongan
from . import pangkat
from . import golongan
from . import mutasi_jabatan
from . import jabatan
from . import mutasi_kenaikan_gaji_berkala
from . import mutasi_penyesuaian_masa_kerja
from . import mutasi_pengajuan_angka_kredit
from . import mutasi_penetapan_angka_kredit
from . import mutasi_hukum
from . import mutasi_status_detail
from . import matra
from . import fakultas
from . import mutasi_unit_deatil
from . import mutasi_pang_gol_detail
from . import mutasi_jabatan_detail
from . import mutasi_gaji_detail
from . import masa_kerja_detail
from . import mutasi_ak_detail
from . import mutasi_pak_detail
from . import mutasi_hukum_detail
from . import mutasi_jabatan_struktural
from . import mutasi_jabatan_struktural_detail
from . import mutasi_skp