#-*- coding: utf-8 -*-

{
	"name": "Vit marketing sph garment",
	"version": "1.4", 
	"depends": [
		'base','stock','product','uom','account','purchase','vit_marketing','vit_marketing_inherit',
		'vit_marketing_inquery_garmen','vit_marketing_proposal',
	],
	"author": "SLH[vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit marketing sph module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"data/squence.xml",
		"security/group.xml",
		"security/ir.model.access.csv",
		# "view/menu.xml",
		"wizard/sph_wizard.xml",
		"view/marketing_sph.xml",
		"view/boq_sph_line.xml",
		# "view/doc_sph_line.xml",
		"report/paperformat.xml",
		"report/template.xml",
		"report/marketing_sph.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}