#!/usr/bin/python
from . import jenis_insentif_kinerja
from . import jenis_sub_insentif_kinerja
from . import employee
from . import grade_per_pegawai_detail
from . import gaji_pnbp_detail
from . import pir_detail
from . import tunkin_kehadiran_detail
from . import kehadiran_pegawai_detail
from . import remunerasi_pegawai_ids
from . import capaian_kinerja_unit_kerja_detail
from . import unit_kerja
from . import grade_per_pegawai
from . import gaji_pnbp
from . import pir
from . import tunkin_terlambat_detail
from . import tunkin_pulang_detail
from . import tunkin_pemotongan_detail
from . import tunkin_kehadiran
from . import tunkin_terlambat
from . import tunkin_pulang
from . import tunkin_pemotongan
from . import kehadiran_pegawai
from . import remunerasi_pegawai
from . import capaian_kinerja_unit_kerja