#-*- coding: utf-8 -*-

{
	"name": "Laporan Inherited",
	"version": "1.1", 
	"depends": [
		'base','hr','vit_univ_common',
		'vit_laporan','vit_riwayat',
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Laporan module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"view/laporan_daftar_pegawai.xml",
		"view/pensiun.xml",
		"view/daftar_riwayat_hidup.xml",
		"view/duk.xml",
		"view/daftar_guru_besar.xml",
		"view/tenaga_fungsional.xml",
		"view/dp3.xml",
		"view/kenaikan_gaji.xml",
		"view/kenaikan_pangkat.xml",
		"view/lap_nominatif.xml",
		"view/penerimaan_penghargaan.xml",
		"view/laporan_statistik_pegawai.xml",
		"view/pertumbuhan_pegawai.xml",
		"view/laporan_daftar_pegawai_status.xml",
		"view/penetapan_angka_kredit.xml",
		"view/ringkasan_kepegawaian.xml",
		"data/sequence_laporan_daftar_pegawai.xml",
		"data/sequence_laporan_statistik_pegawai.xml",
		"data/sequence_daftar_riwayat_hidup.xml",
		"data/sequence_duk.xml",
		"data/sequence_daftar_guru_besar.xml",
		"data/sequence_tenaga_fungsional.xml",
		"data/sequence_dp3.xml",
		"data/sequence_kenaikan_gaji.xml",
		"data/sequence_kenaikan_pangkat.xml",
		"data/sequence_daftar_pegawai_pensiun.xml",
		"data/sequence_lap_nominatif.xml",
		"data/sequence_penerimaan_penghargaan.xml",
		"data/sequence_pertumbuhan_pegawai.xml",
		"data/sequence_laporan_daftar_pegawai_status.xml",
		"data/sequence_penetapan_angka_kredit.xml",
		"data/sequence_ringkasan_kepegawaian.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}