#-*- coding: utf-8 -*-

{
	"name": "SKP Inherited",
	"version": "1.0", 
	"depends": [
		'base','hr','vit_univ_common','vit_skp'
	],
	"author": "SLH [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the SKP module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"data/sequence_skp.xml",
		"data/sequence_target_skp.xml",
		"data/sequence_penilaian_skp.xml",
		"data/sequence_monitor_skp.xml",
		"view/menu.xml",
		"view/skp.xml",
		"view/target_skp.xml",
		"view/skp_tugas_tambahan.xml",
		"view/target_skp.xml",
		"view/penilaian_skp.xml",
		"view/mon_skp.xml",
		"report/target_skp.xml",
		"report/pengukuran_skp.xml",
		"report/penilaian_skp.xml",
		"report/monitoring_skp.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}